In [1]:
import numpy as np
x = np.ones([7,5])
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
x = np.zeros([4,6])
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [3]:
def framed_zeros(num_rows,num_cols):
    x = np.ones((num_rows,num_cols))
    x[1:-1,1:-1] = 0
    return x 
   
print(framed_zeros(6, 5))

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:

def alternate_ones_zeros(num_rows,num_cols):
    x = np.zeros((num_rows,num_cols))
    x[::2, ::2] = 1
    x[1::2, 1::2] = 1
    return x
    


print(alternate_ones_zeros(5, 5))

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


In [5]:
def invert_binary(x):
    return 1 - x


x = np.array([[1, 0, 0, 1], [0, 0, 1, 1], [0, 0, 1, 1]])
print(invert_binary(x))

[[0 1 1 0]
 [1 1 0 0]
 [1 1 0 0]]


In [6]:
def merge_with_binary_mask(x, y, binary_mask):
    return x * (1 - binary_mask) + y * binary_mask

x = np.array([[4, 2, 3, 6], [7, 6, 8, 9], [8, 1, 4, 5]])
y = np.array([[0, 9, 4, 1], [3, 5, 3, 2], [4, 7, 9, 0]])
binary_mask = np.array([[0, 1, 1, 0], [1, 0, 1, 0], [0, 0, 1, 1]])
print(merge_with_binary_mask(x, y, binary_mask))

[[4 9 4 6]
 [3 6 3 9]
 [8 1 9 0]]


In [8]:
int_0_to_100 = np.arange(0,101)
print(int_0_to_100)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [9]:
even_2_to_1000 = np.arange(2,1001,2)
print(even_2_to_1000)

[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
   30   32   34   36   38   40   42   44   46   48   50   52   54   56
   58   60   62   64   66   68   70   72   74   76   78   80   82   84
   86   88   90   92   94   96   98  100  102  104  106  108  110  112
  114  116  118  120  122  124  126  128  130  132  134  136  138  140
  142  144  146  148  150  152  154  156  158  160  162  164  166  168
  170  172  174  176  178  180  182  184  186  188  190  192  194  196
  198  200  202  204  206  208  210  212  214  216  218  220  222  224
  226  228  230  232  234  236  238  240  242  244  246  248  250  252
  254  256  258  260  262  264  266  268  270  272  274  276  278  280
  282  284  286  288  290  292  294  296  298  300  302  304  306  308
  310  312  314  316  318  320  322  324  326  328  330  332  334  336
  338  340  342  344  346  348  350  352  354  356  358  360  362  364
  366  368  370  372  374  376  378  380  382  384  386  388  390  392
  394 

In [12]:
def numbered_table(size):
    return np.arange(1, size * size + 1).reshape((size, size))


print(numbered_table(3))
print(numbered_table(5))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
def dim1_to_dim2(x):
    return x[np.newaxis,:]


x = np.array([4, 2, 7, 1])
print(dim1_to_dim2(x))

[[4 2 7 1]]


In [14]:
def row_to_col(x):
    return x[:,np.newaxis]


x = np.array([4, 2, 7, 1])
print(row_to_col(x))

[[4]
 [2]
 [7]
 [1]]


In [15]:
fives = np.full((10,10),5)
print(fives)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [16]:
x = np.ones((10, 10))
x[0:5, 5:10] = 2
x[5:10, 0:5] = 3
x[5:10, 5:10] = 4
print(x)

[[1. 1. 1. 1. 1. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 4. 4. 4. 4. 4.]]


In [17]:
corner = np.arange(1, 26).reshape(5, 5)
x = np.tile(corner, (2, 2))
print(x)

[[ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]
 [11 12 13 14 15 11 12 13 14 15]
 [16 17 18 19 20 16 17 18 19 20]
 [21 22 23 24 25 21 22 23 24 25]
 [ 1  2  3  4  5  1  2  3  4  5]
 [ 6  7  8  9 10  6  7  8  9 10]
 [11 12 13 14 15 11 12 13 14 15]
 [16 17 18 19 20 16 17 18 19 20]
 [21 22 23 24 25 21 22 23 24 25]]
