# The Purpose of this project is to select elements from NumPy Array

In [1]:
import numpy as np
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
x = np.array(values)
even = x[::2]
print(even)

[7 5 9 1 2]


In [2]:
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
x = np.array(values)
odd = x[1::2]
print(odd)

[4 8 0 3 6]


In [3]:
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
x = np.array(values)
reverse = np.flip(x,axis = 0)
print(reverse)

[6 2 3 1 0 9 8 5 4 7]


In [4]:
def first_half(x):
    return x[:len(x)//2]

x = np.array([1, 2, 3, 4])
print(first_half(x))

x = np.array([1, 2, 3, 4, 5])
print(first_half(x))

[1 2]
[1 2]


In [5]:
def second_half(x):
    return x[len(x)//2:]

x = np.array([1, 2, 3, 4])
print(second_half(x))

x = np.array([1, 2, 3, 4, 5])
print(second_half(x))

[3 4]
[3 4 5]


In [6]:
values1 = [5, 7, 4, 6, 3, 9]
values2 = [2, 1, 8, 0]
x = np.array(values1)
y = np.array(values2)
concat = np.concatenate([x,y])
print(concat)

[5 7 4 6 3 9 2 1 8 0]


In [7]:
def mix(x,y):
    return np.concatenate([x[:len(x)//2], y[len(y)//2:]])
    

x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 8, 9, 10])
z = mix(x, y)
print(z)

[ 1  2  8  9 10]


In [8]:
values = [7, 4, 5, 8, 9, 0, 1, 3, 2, 6]
x = np.array(values)
reverse_skip = x[::-2]
print(reverse_skip)

[6 3 0 8 4]


In [9]:
values = [
    [5, 6, 5, 5, 8, 9, 9], 
    [9, 5, 1, 4, 5, 9, 7], 
    [3, 9, 6, 2, 1, 2, 3], 
    [1, 7, 6, 7, 1, 7, 5], 
    [2, 1, 3, 8, 7, 8, 8], 
    [2, 9, 3, 6, 4, 6, 4]
]
x = np.array(values)
reverse_2d = x[::-1, ::-1]
print(reverse_2d)

[[4 6 4 6 3 9 2]
 [8 8 7 8 3 1 2]
 [5 7 1 7 6 7 1]
 [3 2 1 2 6 9 3]
 [7 9 5 4 1 5 9]
 [9 9 8 5 5 6 5]]


In [10]:
def select_rows(x, row_indexes):
    return x[row_indexes]

x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
rows_1_4_3 = select_rows(x, [1, 4, 3])
print(rows_1_4_3)

[[ 5  6  7  8]
 [17 18 19 20]
 [13 14 15 16]]


In [11]:
def select_columns(x, col_indexes):
    return x[:,col_indexes]


x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20]])
cols_3_0 = select_columns(x, [3, 0])
print(cols_3_0)

[[ 4  1]
 [ 8  5]
 [12  9]
 [16 13]
 [20 17]]


In [12]:
def copy_row_k_times(x,row_index,num_copies):
    return x[[row_index] * num_copies]


x = np.array([[ 1,  2,  3,  4], [ 5,  6,  7,  8], [ 9, 10, 11, 12]])
row_k_times = copy_row_k_times(x, 1, 4)
print(row_k_times)

[[5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [13]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])
x = array2d[:,[1,2]]
y = array2d[[0,2],:]
z = array2d[2,[1,2,3]]
print(x)
print(y)
print(z)

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[12 13 14]


In [14]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])
x = array2d[1::2,::2]
y = array2d[::2,1::2]
z = array2d[::2,1:4]
print(x)
print(y)
print(z)

[[ 6  8 10]
 [16 18 20]]
[[ 2  4]
 [12 14]]
[[ 2  3  4]
 [12 13 14]]


In [15]:
array2d = np.array([
    [ 1,  2,  3,  4,  5],
    [ 6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
])
x = array2d[:,[2,3,4]]
y = array2d[1::,[1,2,3,4]]
z = array2d[:-1,:-1]
print(x)
print(y)
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [16]:
def swap_rows(x,row_index1,row_index2):
    x[[row_index1,row_index2]] = x[[row_index2,row_index1]]
    
x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_rows(x, 0, 2)
print(x)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [17]:
def swap_cols(x,col_index1,col_index2):
    x[:,[col_index1,col_index2]] = x[:,[col_index2,col_index1]]

x = np.array([[1,  2,  3,  4], [5,  6,  7,  8], [9, 10, 11, 12]])
swap_cols(x, 0, 1)
print(x)

[[ 2  1  3  4]
 [ 6  5  7  8]
 [10  9 11 12]]
